// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "d7e2fea916659bbf271b4632f028fed5"
    },
    {
        "url": "icon-96.png",
        "revision": "f1bdf68dd999551760088eb79f5cbcba"
    },
    {
        "url": "icon-128.png",
        "revision": "1ec8980d1a4a78149a5ec7aac0a52a79"
    },
    {
        "url": "icon-144.png",
        "revision": "70839b0a9ce56b64a72ca87b9c29f139"
    },
    {
        "url": "icon-152.png",
        "revision": "24fd20976f6dc6d81b99bdecd571fced"
    },
    {
        "url": "icon-192.png",
        "revision": "286958b45be08bdc916b8e3126b2203d"
    },
    {
        "url": "icon-384.png",
        "revision": "d3d46f60ff5014f7d85d047e1c55329f"
    },
    {
        "url": "icon-512.png",
        "revision": "1a98134a086859d517de611e9e0579bc"
    },
    {
        "url": "favicon.ico",
        "revision": "7cbcf8be98d3ce63133537d07504db0f"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "d3ceb161cfab9e9c5f40a93e15e5be27"
    },
    {
        "url": "client readme.md",
        "revision": "ab31bfea897d87b5966d656afd7b038d"
    },
    {
        "url": "client readme.pdf",
        "revision": "a1a179bf269ec4b8c90c50fbc641cfa7"
    },
    {
        "url": "features and functionalities.md",
        "revision": "7194c8ff4cb8ba0448eb922409c12484"
    },
    {
        "url": "index.html",
        "revision": "f7ffb679ee6124b13f3e2dd22d20cfab"
    },
    {
        "url": "manifest.json",
        "revision": "f0e2a6bf969c56b5c84f34d5047ede96"
    },
    {
        "url": "offline.html",
        "revision": "ad17d01f02bb01615fbc0509f5aee82a"
    },
    {
        "url": "pwa-register.js",
        "revision": "3ec872e4f752840ad8f85922ff6cebe7"
    },
    {
        "url": "readme.md",
        "revision": "70193bdb7093cdfaec30dafc2ce5e745"
    },
    {
        "url": "sw.js",
        "revision": "81bab11f28e65f2ab87fe09a0ea117df"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}